#!/bin/bash
#
# Fakebox, a simple cross-compilation toolkit
#
# Copyright (C) 2007-2008 by Pawel Foremski <pjf@asn.pl>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place - Suite 330, Boston, MA 02111-1307, USA.
#
# vim: tw=120
#

config="${1:-./fakebox.conf}"
[ "$2" = "-f" ] && register="1"

###
### configuration
###

[ -d "$config" ] && config="$config/fakebox.conf"
if [ ! -f "$config" ]; then
	echo "Error: configuration file not found: $config" >&2
	exit 1
fi

# load config
source $config

# load local config changes
[ -f "$config.local" ] && source "$config.local"

###
### defaults
###

# paths to toolchain and virtual root, relative to $FB_TOP
FB_TOOLCHAIN=${FB_TOOLCHAIN:-toolchain}
FB_ROOTFS=${FB_ROOTFS:-rootfs}

# absolute path to top dir, containing configs, toolchain, etc
FB_TOP=${FB_TOP:-`pwd`}

# wrapper prefix
FB_WRAP="${FB_WRAP:-$FB_TOP/$FB_TOOLCHAIN/bin/$FB_PREFIX}"

# path to fakebox
FB_PATH=${FB_PATH:-$FB_TOP/fakebox}

# id displayed in bash prompt
FB_NAME=${FB_NAME:-fakebox}

export FB_TOOLCHAIN FB_ROOTFS FB_WRAP FB_TOP FB_PATH FB_NAME

# local modifications
[ -e "${config%.conf}-local.conf" ] && source "${config%.conf}-local.conf"

# path
if [ -z "$FB_LEAVE_PATH" ]; then
	PATH="$FB_PATH/wrappers:$FB_PATH/pkgtools"
	PATH="$PATH:$FB_TOP/$FB_TOOLCHAIN/bin"
#	PATH="$PATH:$FB_TOP/$FB_ROOTFS/bin:$FB_TOP/$FB_ROOTFS/usr/bin"
#	PATH="$PATH:$FB_TOP/$FB_ROOTFS/sbin:$FB_TOP/$FB_ROOTFS/usr/sbin"
	PATH="$PATH:$HOME/bin:$HOME/local/bin:/usr/local/bin:/usr/local/sbin"
	PATH="$PATH:/usr/bin:/usr/sbin:/bin:/sbin"

	[ -d "$FB_TOP/bin" ] && PATH="$PATH:$FB_TOP/bin"

	export PATH
fi

# hack for c preprocessor in some weird toolchains
export CPP="cpp"

# shortcuts
export FB_ROOTDIR=$FB_TOP/$FB_ROOTFS
export FB_TOOLSDIR=$FB_TOP/$FB_TOOLCHAIN/bin

# magic flag
export FAKEBOX=1

###
### pkg tools
###
source ${FB_MAKEPKG_CONF:-makepkg.conf}

###
### qemu
###

if [ -n "$FB_QEMU" ]; then
	# 0x7f, ELF, \0, { 1 - LE, 2 - BE }, 12 x 0x00, 2-byte arch ID in given endianness
	# XXX: below supports big-endians only
	MAGIC=`
	echo -n "\x7f\x45\x4c\x46\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
	case "$FB_QEMU" in
		ppc)   echo -n "\x14";;
		mips)  echo -n "\x08";;
		armeb) echo -n "\x28";;
		*)     echo "Unsupported arch: $FB_QEMU" >&2; exit 1;;
	esac`

	notsupported=$?
	MASK="\xff\xff\xff\xff\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff"
	MAGIC_PLAIN=${MAGIC//\\x/}
	MASK_PLAIN=${MASK//\\x/}
else
	notsupported=1
fi

if [ $notsupported -eq 0 ]; then
	# check if binfmt_misc is already loaded
	if [ ! -e /proc/sys/fs/binfmt_misc/register ]; then
		echo "Using sudo to load and init binfmt_misc module"
		sudo modprobe binfmt_misc || exit 1
		sudo mount -t binfmt_misc none /proc/sys/fs/binfmt_misc || exit 1
	fi

	# remove any existing registration with the same magic
	for f in /proc/sys/fs/binfmt_misc/*; do
		[ "`basename $f`" != "register" ] || continue
		{ [ "$register" = "1" ] || [ "`basename $f`" != "fakebox-$FB_QEMU" ]; } || continue
		[ -e "$f" ] || exit 1
		grep -q "magic $MAGIC_PLAIN" $f || continue
		grep -q "mask $MASK_PLAIN" $f || continue
		echo -e "\nWarning: Removing existing binfmt_misc wrapper: `basename $f` (using sudo)"
		echo "-1" | sudo dd of=$f status=noxfer || exit 1
	done

	if [ ! -f /proc/sys/fs/binfmt_misc/fakebox-$FB_QEMU ]; then
		[ "`id -u`" != "0" ] && \
			echo -e "\nWarning: Using sudo to register $FB_QEMU qemu wrapper"

		# register us
		# XXX: no 2>/dev/null for dd's crappy msgs in order to see errors
		echo "Registering fakebox-$FB_QEMU in binfmt_misc"
		{
			echo -n ":fakebox-$FB_QEMU:M:0:$MAGIC:$MASK:"
			if [ -e "/usr/lib/fakebox-qemuwrap:" ]; then
				echo "/usr/lib/fakebox-qemuwrap:"
			else
				echo "$FB_PATH/wrappers/qemuwrap:"
			fi
		} | sudo dd of=/proc/sys/fs/binfmt_misc/register status=noxfer || exit 1

		if [ -e /proc/sys/vm/mmap_min_addr ]; then
			echo "Fixing mmap bug"
			echo 4096 | sudo dd of=/proc/sys/vm/mmap_min_addr status=noxfer || exit 1
		fi
	fi
fi

###
### start
###

# run shell
/bin/bash --noprofile --rcfile "${FB_BASHRC:-$FB_PATH/bashrc}"
