#!/bin/sh
#
# Execute proper qemu
#

qemu="${FB_QEMU_PATH:-qemu}-$FB_QEMU"
libdir="${FB_OPENWRT_ROOTFS:-$FB_ROOTFS}"

[ "$FB_DEBUG" = "3" ] && echo " [FB]  qemu: $qemu -L $libdir $@" >&2
exec $qemu -L "$libdir" "$@"
