#!/bin/sh

if [ "$FB_OFF" = "1" ]; then exec "/bin/uname" "$@"; fi

option="$1"
set -- $FB_UNAME

case "$option" in
	"") echo "$1";;
	-a) echo "$*";;
	-m) echo "${11}";;
	-n) echo "$2";;
	-r) echo "$3";;
	-s) echo "$1";;
	-p) echo "${12}";;
	-v) echo "$4 $5 $6 $7 $8 $9 ${10}";;
	*) echo "uname-wrapper: unknown option: $option" >&2; exit 1;;
esac

exit 0
