#!/bin/bash
#
# Wrapper around toolchain
# The place where the fakebox magic takes place
#

# original tool name
ME="`basename $0`"

# hacky
[ "$FB_OFF" = "1" ] && exec "/usr/bin/$ME" "$@"

# special case
[ "$ME" = "strip" ] && exec "$FB_WRAP-$ME" "$@"

# prefix absolute /usr paths with $FB_TOP
for i in "$@"; do args[${#args[@]}]="${i//\/usr/$FB_TOP/usr}"; done

# handle special cases
[ "$1" = "-V" ] || case "$ME" in
	gcc|ld|cc)
		args[${#args[@]}]="--sysroot=$FB_TOP/$FB_ROOTFS"
		addargs="$FB_WRAP_ADD"
		;;
esac

# exec proper tool
[ "$FB_DEBUG" = "1" ] && echo "$FB_WRAP-$ME" "${args[@]}" $addargs >&2
exec "$FB_WRAP-$ME" "${args[@]}" $addargs
