#!/bin/bash
#
# Wrapper around toolchain
# The place where the fakebox magic takes place
#

# original tool name
ME="`basename $0`"

[ "$FB_DEBUG" = "1" ] && echo "  [FB]  called: $ME $@" >&2

# hacks
[ "$FB_OFF" = "1" ] && exec "/usr/bin/$ME" "$@"
[ "$ME" = "strip" ] && exec "$FB_WRAP-$ME" "$@"
[ "$ME" = "cc" ] && ME=gcc

# prefix absolute /usr paths with $FB_TOP
for i in "$@"; do
	i="${i//I\/usr/$FB_TOP/usr}"
	args[${#args[@]}]="${i// \/usr/$FB_TOP/usr}"
done

# handle special cases
[ "$1" = "-V" ] || case "$ME" in
	gcc|ld|cc) args[${#args[@]}]="--sysroot=$FB_TOP/$FB_ROOTFS";;
esac

# exec proper tool
[ "$FB_DEBUG" = "1" ] && echo "  [FB]  result: $FB_WRAP-$ME" "${args[@]}" $FB_WRAP_ADD >&2
exec "$FB_WRAP-$ME" "${args[@]}" $FB_WRAP_ADD
