#!/bin/bash
#
# genmd5, part of Arch Linux's makepkg
#
# Copyright (C) 2002-2004 Judd Vinet <jvinet@zeroflux.org>
# Copyright (C) 2005-2009 ASN Sp. z o.o.
#
# Authors: Pawel Foremski <pjf@asn.pl>
#          Michał Wróbel <maw@asn.pl>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
# USA.
#
# TODO: share some code with makepkg
#

myver='0.21'
startdir=`pwd`


### SUBROUTINES ###
msg() { echo "==> $1" >&2; }
warning() { echo "==> WARNING: $1" >&2; }
error() { echo "==> ERROR: $1" >&2; msg "Aborting..."; exit ${2:-1}; }

strip_url() { echo $1 | sed 's|^.*://.*/||g'; }

usage() {
	echo "genmd5 version $myver"
	echo "usage: $0 [options]"
	echo "options:"
	echo "  -h, --help       This help"
	echo "  -p <buildscript> Use an alternate build script (instead of PKGBUILD)"
	echo
	echo "  if -p is not specified, makepkg will look for a PKGBUILD"
	echo "  file in the current directory."
	echo
}

# options
BUILDSCRIPT="./PKGBUILD"

ARGLIST=$@
while [ "$#" -ne "0" ]; do
	case $1 in
		--help) usage; exit 0 ;;
		--*)    usage; exit 1 ;;
		-*)
			while getopts "p:-" opt; do
				case $opt in
					h) usage; exit 0 ;;
					p) BUILDSCRIPT=$OPTARG ;;
					-) OPTIND=0; break ;;
					*) usage; exit 1 ;;
				esac
			done
			;;
		*) true ;;
	esac
	shift
done

unset pkgname pkgver pkgrel md5sums source install build
umask 0022

### prepare
[ ! -f $BUILDSCRIPT ] && error "$BUILDSCRIPT does not exist."
source $BUILDSCRIPT

[ `echo $pkgver | grep '-'` ] && error "pkgver is not allowed to contain hyphens."
[ `echo $pkgrel | grep '-'` ] && error "pkgrel is not allowed to contain hyphens."

msg "Generating MD5 sums for package: $pkgname (`date`)"
cd $startdir

# retrieve sources
msg "Retrieving sources..."
mkdir -p $FB_PKGDW
cd $FB_PKGDW

for netfile in ${source[@]}; do
	file=`strip_url $netfile`

	if [ -f $file ]; then
		msg "    Found $file in build dir"
	else
		[ -z "$FB_FTPAGENT" ] && error "FTPAGENT is not configured."
		ftpclient=`echo $FB_FTPAGENT | awk {'print $1'}`
		[ -z "`which $ftpclient 2> /dev/null`" ] && error "ftpclient `basename $ftpclient` is not installed."

		proto=`echo $netfile | sed 's|://.*||'`
		[ "$proto" != "ftp" -a "$proto" != "http" -a "$proto" != "https" ] && \
			error "$netfile was not found in the build directory and is not a proper URL."

		msg "    Downloading $file"
		$FB_FTPAGENT $netfile 2>&1
		[ ! -f $file ] && error "Failed to download $file"
	fi
done

# generate md5 hashes
[ ! `type -p md5sum` ] && error "Cannot find the md5sum program."

msg "Generating MD5 sums for source files"
echo

ct=0
newline=0
numsrc=${#source[@]}

for netfile in ${source[@]}; do
	file=`strip_url $netfile`
	sum=`md5sum $file | cut -d' ' -f 1`

	if [ $ct -eq 0 ]; then
		echo -n "md5sums=("
	else
		[ $newline -eq 0 ] && echo -n "         "
	fi

	echo -n "'$sum'"
	let ct++

	if [ $ct -eq $numsrc ]; then
		echo ')'
	else
		if [ $newline -eq 1 ]; then
			echo ' \'
			newline=0
		else
			echo -n ' '
			newline=1
		fi
	fi
done

echo
exit 0
