#!/bin/sh
#
# Quite simple script which generates package.list.gz and package.md5.gz files
# needed by Lintrack package repositories
#
# Copyright (C) 2006-2009 ASN Sp. z o.o.
#
# Authors: Pawel Foremski <pjf@asn.pl>
#          Michal Wrobel <xmxwx@asn.pl>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place - Suite 330, Boston, MA 02111-1307, USA.
#

pkgs="`ls *.pkg.tar.gz`"
[ $? -ne 0 ] && exit 1

(
	echo "#"
	echo "# Lintrack package repository listing"
	echo "# Latest package versions as of `date`"
	echo "#"
	echo "# package | pkgver | pkgrel | fixrel"
	echo "#"
	echo

	# 1. sort by pkgrel
	# 2. add fields containing parts of pkgver and use them as sort keys
	#    (all non-digits are neglected, digits are interpreted as numbers)
	# 3. select only the last packages (achieved by sort -r and sort -u)
	# 4. cut the split pkgver off
	#
	# To sort pkgver multiple stable sorts with subsequent fields as keys are
	# used (poor man's radix-sort). Also, sed's greediness is of use :P
	echo -e "$pkgs" \
		| grep -v '\-big.pkg.tar.gz' \
		| sed -re 's/(.*)-(.*)-(.*)-(.*).pkg.tar.gz/\1 \2 \3 \4/g' \
		| sort -rn -k1,4 \
		| awk '{v=$2; gsub("[^0-9]+", " ", v); print $1" "$2" "$3" "$4" "v}' \
		| sort -srn -k10,10 | sort -srn -k9,9 | sort -srn -k8,8 \
		| sort -srn -k7,7 | sort -srn -k6,6 | sort -srn -k5,5 \
		| sort -s -k1,1 -u | cut -d' ' -f1-4
) > package.list
echo "$((`cat package.list | wc -l` - 7)) packages listed in package.list"

(
	echo "#"
	echo "# Lintrack package repository listing"
	echo "# MD5 and SHA1 sums, file sizes"
	echo "#"
	echo "# file | md5sum | sha1sum | size"
	echo "#"
	echo

	for file in $pkgs; do
		echo -n "$file "
		echo -n "`md5sum $file | cut -b1-32` "
		echo -n "`sha1sum $file | cut -b1-40` "
		echo "`du -b $file | cut -f1`"
	done
) > package.md5
echo "$((`cat package.md5 | wc -l` - 7)) packages listed in package.md5"

# TODO: sign package.md5 with GPG
