#!/bin/sh
#
# Quite simple script which generates package.list.gz and package.md5.gz files
# needed by Lintrack package repositories
#

pkgs="`ls *.pkg.tar.gz`"
[ $? -ne 0 ] && exit 1

(
	echo "#"
	echo "# Lintrack package repository listing"
	echo "# Latest package versions as of `date`"
	echo "#"
	echo "# package | pkgver | pkgrel | fixrel"
	echo "#"
	echo

	# 1. sort by pkgrel
	# 2. add fields containing parts of pkgver and use them as sort keys
	#    (all non-digits are neglected, digits are interpreted as numbers)
	# 3. select only the last packages (achieved by sort -r and sort -u)
	# 4. cut the split pkgver off
	#
	# To sort pkgver multiple stable sorts with subsequent fields as keys are
	# used (poor man's radix-sort). Also, sed's greediness is of use :P
	echo -e "$pkgs" \
		| grep -v '\-big.pkg.tar.gz' \
		| sed -re 's/(.*)-(.*)-(.*)-(.*).pkg.tar.gz/\1 \2 \3 \4/g' \
		| sort -rn -k1,4 \
		| awk '{v=$2; gsub("[^0-9]+", " ", v); print $1" "$2" "$3" "$4" "v}' \
		| sort -srn -k10,10 | sort -srn -k9,9 | sort -srn -k8,8 \
		| sort -srn -k7,7 | sort -srn -k6,6 | sort -srn -k5,5 \
		| sort -s -k1,1 -u | cut -d' ' -f1-4
) | gzip > package.list.gz
echo "$((`zcat package.list.gz | wc -l`-7)) packages listed in package.list.gz"

(
	echo "#"
	echo "# Lintrack package repository listing"
	echo "# MD5 and SHA1 sums, file sizes"
	echo "#"
	echo "# file | md5sum | sha1sum | size"
	echo "#"
	echo

	for file in $pkgs; do
		echo -n "$file "
		echo -n "`md5sum $file | cut -b1-32` "
		echo -n "`sha1sum $file | cut -b1-40` "
		echo "`du -b $file | cut -f1`"
	done
) | gzip > package.md5.gz
echo "$((`zcat package.md5.gz | wc -l`-7)) files listed in package.md5.gz"
