#!/bin/bash
#
# installpkglocal
# Simple tool which installs package locally
#
# This file is licensed under GNU GPL 2, for full license text see file
# called "COPYING" in main distribution directory
#
# TODO: maybe unify with normal (Lintrack's) install/upgradepkg tools
#

readonly VARDIR=var/pkg

[ -z "$1" ] && { echo "Usage: $0 package.pkg.tar.gz [ root_dir ]" >&2; exit 1; }
[ -f "$1" ] || { echo "$1: no such file" >&2; exit 1; }

cd `dirname $1` || exit 1
pkgdir=`pwd`
pkgname=`basename $1`
pkg="$pkgdir/$pkgname"

case "`basename $0`" in
	installpkglocal) title="Installing"; call="install";;
	upgradepkglocal) title="Upgrading";  call="upgrade";;
	*) echo "Call me as installpkglocal/upgradepkglocal"; exit 1;;
esac

rootdir="${2:-$FB_TOP/$FB_ROOTFS}"

echo "Installing $pkgname in $rootdir"
cd $OLDPWD || exit 1
mkdir -p $rootdir && cd $rootdir || exit 1

echo -n "Fetching package information: "
set -- `echo "$pkgname" | sed -re 's/^(.*)-(.*)-([0-9]+)-([0-9]+).*/\1 \2 \3 \4/g'`
pkgname="$1"
fixrel="$4"
pkgver="$2-$3-$fixrel"
echo "$pkgname $2-$3 fixrel $fixrel"

tar -xzf $pkg .FIX 2>/dev/null && {
	echo "Is a fixrel package"
	echo "Running FIX script in chroot `pwd` (need root)"
	sudo /usr/sbin/chroot . /bin/bash .FIX || { echo "Error - aborting" >&2; exit 1; }
}

tar -xzf $pkg .INSTALL 2>/dev/null && {
	echo "Running pre_$call in chroot `pwd` (need root)"
	sudo /usr/sbin/chroot . /bin/bash .INSTALL pre_$call $pkgver || { echo "Error - aborting" >&2; exit 1; }
	runpostinstall=1
}

echo "Extracting..."
tar -xzf $pkg || { echo "Error - aborting" >&2; exit 1; }

[ "$runpostinstall" = 1 ] && {
	echo "Running post_$call in chroot `pwd` (need root)"
	sudo /usr/sbin/chroot . /bin/bash .INSTALL post_$call $pkgver \
		|| echo "WARNING: error while running post_$call" >&2
}

if [ "$fixrel" = "1" ]; then
	echo "Updating package info in local pkg database"
	mkdir -p "$VARDIR/$pkgname"
	echo "$pkgver" > "$VARDIR/$pkgname/installed"
	cp -f .PKGINFO "$VARDIR/$pkgname/PKGINFO"
	cp -f .FILELIST "$VARDIR/$pkgname/FILELIST"
else
	echo "Updating fixrel info in local pkg database"
	echo "$pkgver" > "$VARDIR/$pkgname/installed"
fi

echo "Cleanup"
rm -f ./.* 2>/dev/null

echo "Done"

# vim: set tw=120
